name: Alerta MET REDEMET

on:
  schedule:
    - cron: '*/15 * * * *' # A cada 15 minutos, por exemplo
  workflow_dispatch: # Permite execução manual

jobs:
  run_alert_agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Ou a versão que você usa

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz # Adicione outras dependências se tiver

      - name: Baixar Cache de Alertas Anterior
        uses: dawidd6/action-download-artifact@v3
        with:
          # Nome do workflow (pode ser o nome do arquivo .yml sem a extensão, ou o nome definido no workflow)
          # Se o nome do seu arquivo de workflow é 'main.yml', github.workflow é 'Alerta MET REDEMET' (o nome no topo)
          workflow: ${{ github.workflow }}
          # Tenta baixar da mesma branch que está executando
          branch: ${{ github.ref_name }}
          # Nome do artefato que vamos usar para o cache
          name: persistent-alert-cache-artifact
          # Caminho para onde o arquivo será baixado (raiz do workspace)
          path: .
          # O que fazer se nenhum artefato for encontrado (importante para a primeira execução)
          if_no_artifact_found: ignore # Pode ser 'warn' ou 'fail' se preferir

      - name: Executar o script de alerta
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REDEMET_API_KEY: ${{ secrets.REDEMET_API_KEY }}
        run: python alerta_redemet_agente.py

      - name: Fazer Upload do Novo Cache de Alertas
        uses: actions/upload-artifact@v4
        with:
          # Mesmo nome do artefato usado no download
          name: persistent-alert-cache-artifact
          # Caminho do arquivo de cache que o script Python salvou
          path: persistent_alert_cache.json
          # Opcional: por quanto tempo manter o artefato (padrão é 90 dias)
          # retention-days: 7
