name: Alerta MET REDEMET

on:
  schedule:
    # Executa a cada 15 minutos. Você pode ajustar este valor.
    - cron: '*/15 * * * *'
  workflow_dispatch: # Permite que você execute este workflow manualmente na aba "Actions" do GitHub

jobs:
  run_alert_agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Ou a versão que você usa

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      # --- PASSO MODIFICADO ---
      # Este passo agora usa o seu token pessoal para ter permissão de baixar o cache
      - name: Baixar Cache de Alertas Anterior
        uses: dawidd6/action-download-artifact@v3
        with:
          # Adicionada esta linha para usar o seu Personal Access Token
          github_token: ${{ secrets.ACTIONS_PAT }}
          
          # O resto dos parâmetros continua igual
          workflow: ${{ github.workflow }}
          branch: ${{ github.ref_name }}
          name: persistent-alert-cache-artifact
          path: .
          if_no_artifact_found: ignore

      - name: Executar o script de alerta
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REDEMET_API_KEY: ${{ secrets.REDEMET_API_KEY }}
        run: python alerta_redemet_agente.py

      - name: Fazer Upload do Novo Cache de Alertas
        uses: actions/upload-artifact@v4
        with:
          # O nome do artefato deve ser o mesmo usado no passo de download
          name: persistent-alert-cache-artifact
          # O caminho para o arquivo de cache que o script Python salvou
          path: persistent_alert_cache.json
