name: Agente Inteligência Artificial de Alerta Meteorológico SBTA

on:
  schedule:
    - cron: '*/7 * * * *' # Executa a cada 7 minutos (em UTC)
  workflow_dispatch:

permissions:
  contents: write  # garante que o GITHUB_TOKEN pode dar push

jobs:
  run_alert_agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # usa o token automático do GitHub

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Executar o script de alerta
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REDEMET_API_KEY: ${{ secrets.REDEMET_API_KEY }}
        run: python alerta_redemet_agente.py

      - name: Fazer Commit e Push dos caches atualizados
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@users.noreply.github.com'
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "Chore: Atualiza caches de estado"
            git push
            echo "Caches de estado atualizados e enviados para o repositório."
          else
            echo "Nenhuma alteração nos caches. Nenhum commit necessário."
          fi