name: Monitorar Alertas REDEMET

on:
  schedule:
    # Executa a cada 5 minutos
    # Para testar, você pode usar um intervalo menor ou 'workflow_dispatch'
    # UTC 09:00 é 06:00 BRT, 09:05 é 06:05 BRT, etc.
    # Ajuste '*/5' para o intervalo desejado em minutos
    - cron: '*/5 * * * *' 
  workflow_dispatch: # Permite executar manualmente o workflow

jobs:
  rodar-alerta:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Ou uma versão específica, ex: '3.9'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar o script de alerta
      # As variáveis de ambiente do Telegram devem ser configuradas como secrets no GitHub
      # Vá para Settings > Secrets and variables > Actions > New repository secret
      # Crie TELEGRAM_BOT_TOKEN e TELEGRAM_CHAT_ID
      run: python alerta_redemet_agente.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
