name: Alerta REDEMET (Agendado)

on:
  schedule:
    - cron: '*/10 * * * *' 
  
  workflow_dispatch:

jobs:
  rodar-alerta:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        pip install requests

    - name: Executar o script de alerta
      env: 
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        REDEMET_API_KEY: ${{ secrets.REDEMET_API_KEY }}
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }} # Adicionado
        GIST_ID: ${{ secrets.GIST_ID }}       # Adicionado
      run: |
        python alerta_redemet_agente.py
