name: Agente Alerta REDEMET

on:
  schedule:
    # Executa a cada 5 minutos
    # UTC 09:00 é 06:00 BRT, 09:05 é 06:05 BRT, etc.
    - cron: '*/5 * * * *' 
  workflow_dispatch: # Permite executar manualmente o workflow

jobs:
  run-alert-agent:
    runs-on: ubuntu-latest

    # Variáveis de ambiente para o job inteiro (incluindo secrets)
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      # Garante que a REDEMET_API_KEY esteja disponível como variável de ambiente
      REDEMET_API_KEY: ${{ secrets.REDEMET_API_KEY }}

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Versão específica recomendada para consistência

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        # Instala as dependências listadas em requirements.txt. 
        # Certifique-se de que 'requests' está lá.
        pip install -r requirements.txt

    - name: Executar o script de alerta
      # O script agora pode ler as variáveis de ambiente configuradas no nível do job
      run: python alerta_redemet_agente.py
