name: Agente Inteligência Artificial de Alerta Meteorológico SBTA

on:
  schedule:
    # Executa a cada 10 minutos.
    - cron: '*/10 * * * *'
  workflow_dispatch: # Permite que você execute este workflow manualmente na aba "Actions" do GitHub

jobs:
  run_alert_agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Baixar Cache de Alertas Anterior
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          # Use o nome exato do seu arquivo de workflow
          workflow: main.yml
          branch: ${{ github.ref_name }}
          name: persistent-alert-cache-artifact
          path: .
          # --- ALTERADO AQUI ---
          # Muda de 'ignore' para 'warn' para nos avisar se o cache não for encontrado.
          if_no_artifact_found: warn

      - name: Executar o script de alerta
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REDEMET_API_KEY: ${{ secrets.REDEMET_API_KEY }}
        run: python alerta_redemet_agente.py

      - name: Fazer Upload do Novo Cache de Alertas
        uses: actions/upload-artifact@v4
        with:
          name: persistent-alert-cache-artifact
          path: persistent_alert_cache.json
