name: Agente Alerta REDEMET

on:
  workflow_dispatch: # Permite execução manual
  schedule:
    - cron: '*/5 * * * *' # Executa a cada 5 minutos

jobs:
  run-alert-agent:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      REDEMET_API_KEY: ${{ secrets.REDEMET_API_KEY }} # Adicione esta linha!

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o script de alerta
        run: python alerta_redemet_agente.py
