name: Teste de Agente Simples

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  rodar-script-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        pip install requests

    - name: Executar o script Python
      run: |
        python alerta_redemet_agente.py
