name: Monitorar Alertas REDEMET

on:
  schedule:
    # Executa a cada 5 minutos
    # O cron usa fuso horário UTC. Ajuste conforme necessário para o seu fuso.
    # Ex: '0 12 * * *' para meio-dia UTC
    - cron: '*/5 * * * *' 
  workflow_dispatch: # Permite executar manualmente o workflow pela UI do GitHub

jobs:
  rodar-alerta:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use '3.9', '3.10', etc., se precisar de uma versão específica

    - name: Instalar dependências
      # ESTA É A CORREÇÃO: Garante que o pip leia o requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar o script de alerta
      # Lembre-se: TELEGRAM_BOT_TOKEN e TELEGRAM_CHAT_ID devem ser configurados como Secrets no GitHub.
      # Vá para Settings > Secrets and variables > Actions > New repository secret.
      run: python alerta_redemet_agente.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
