name: Agente Alerta REDEMET
'on':
  workflow_dispatch: null
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run-alert-agent:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
      TELEGRAM_CHAT_ID: '${{ secrets.TELEGRAM_CHAT_ID }}'
      REDEMET_API_KEY: '${{ secrets.REDEMET_API_KEY }}'
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Configurar Python 3.9 (Versão explícita)
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Verificar variáveis de ambiente (DEBUG)
        run: >
          echo "TELEGRAM_BOT_TOKEN_PRESENTE: ${{ env.TELEGRAM_BOT_TOKEN != ''
          }}"

          echo "TELEGRAM_CHAT_ID_PRESENTE: ${{ env.TELEGRAM_CHAT_ID != '' }}"

          echo "REDEMET_API_KEY_PRESENTE: ${{ env.REDEMET_API_KEY != '' }}"

          echo "REDEMET_API_KEY_LENGTH: ${{ env.REDEMET_API_KEY | length }}"
        env:
          REDEMET_API_KEY: '${{ secrets.REDEMET_API_KEY }}'
      - name: Executar o script de alerta
        run: python alerta_redemet_agente.py
