name: Teste de Agente Simples

on:
  # Isso significa que o workflow vai rodar quando você enviar algo para o GitHub
  push:
    branches:
      - main # O nome da sua branch principal (geralmente é 'main' ou 'master')

  # E também permite que você execute manualmente no GitHub
  workflow_dispatch:

jobs:
  rodar-script-python:
    runs-on: ubuntu-latest # O ambiente onde seu código vai rodar (um computador virtual Linux)

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v4 # Pega o seu código do GitHub

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Garante que o Python 3.9 esteja disponível

    - name: Executar o script Python
      run: |
        python meu_primeiro_script.py # Roda o script que você criou
