name: Agente Inteligência Artificial de Alerta Meteorológico SBTA

on:
  schedule:
    # Executa a cada 10 minutos.
    - cron: '*/10 * * * *'
  workflow_dispatch: # Permite que você execute este workflow manualmente na aba "Actions" do GitHub

jobs:
  run_alert_agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      # --- NOVA ABORDAGEM DE CACHE PERSISTENTE ---
      # Substituímos os passos de upload/download por esta action oficial do GitHub
      - name: Carregar/Salvar Cache de Alertas
        uses: actions/cache@v4
        with:
          # O caminho para o arquivo de cache que o script Python usa
          path: persistent_alert_cache.json
          # A chave principal é única para cada execução para garantir que o cache seja sempre salvo no final
          key: alert-cache-${{ github.run_id }}
          # A chave de restauração busca o cache mais recente que começa com "alert-cache-"
          restore-keys: |
            alert-cache-

      - name: Executar o script de alerta
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REDEMET_API_KEY: ${{ secrets.REDEMET_API_KEY }}
        run: python alerta_redemet_agente.py
